Cat col speed improvements
data-day-science/datadayessentials pull request #79
Opened 2023-12-13 17:10 UTC by Colin-Hanley

2023-12-14 12:03 UTC, chris-pickford requested changes
all good, just a couple of minor things

2023-12-14 13:16 UTC, Colin-Hanley commented on datadayessentials/data_transformation/_transformers.py
> +            if 'QCB' in column and column in df_in.columns:
I had the same thought last night, but I now agree that I made wrong choice. I've extracted the QCB filter outside of the function.

2023-12-14 13:33 UTC, whitew1994WW approved these changes
No problems here, nice job 👍

2023-12-14 13:39 UTC, Colin-Hanley commented on datadayessentials/data_transformation/_transformers.py
> +            if 'QCB' in column and column in df_in.columns:
would it not be quicker to send in the correct columns rather than have a loop checking ?

2023-12-18 08:51 UTC, chris-pickford approved these changes
beautiful

2023-12-18 09:24 UTC, merged